version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - /home/$USER/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/$USER/wordpress:/var/www/html
    env_file:
      - .env