JUHYELEE = rebuild

all :
	make -C ${JUHYELEE}
	make -C hywoo
clean :
	make -C ${JUHYELEE} clean
	make -C hywoo clean
fclean :
	make -C ${JUHYELEE} fclean
	make -C hywoo fclean
	rm -rf minishell
re :
	make -C ${JUHYELEE} re
	make -C hywoo re