version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requierments/nginx
    ports:
      - "433:433"
    volumes:
      - /home/$USER/data/wordpress:/var/www/nginx
    depends_on:
      - wordpress
    env_file:
      - ./.env
    restart:
      always
  wordpress:
    container_name: wordpress
    build: ./requierments/wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/$USER/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - ./.env
    restart:
      always
  mariadb:
    container_name: mariadb
    build: ./requierments/mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/$USER/data/mariadb:/var/lib/mysql
    env_file:
      - ./.env
    restart:
      always


# sudo service docker start
# ls -l /var/run/docker.sock
# sudo chmod 666 /var/run/docker.sock