version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "433:433"
    volumes:
      - /home/$USER/wordpress:/var/www/nginx
    depends_on:
      - wordpress
  wordpress:
    build: ./wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/$USER/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
  mariadb:
    build: ./mariadb
    env_file:
      - ./mariadb/conf/default.env
    ports:
      - "3306:3306"
    volumes:
      - /home/$USER/wordpress:/var/lib/mysql


# sudo service docker start
# ls -l /var/run/docker.sock
# sudo chmod 666 /var/run/docker.sock
