version: '3'
networks:
  inception:
    name: inception
services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always
  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - /home/$USER/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always